version: '3.8'

services:
#   authservice:
#     build: ./authservice
#     ports:
#       - "8081:8081"
#     depends_on:
#       - mongo
#     environment:
#       - SPRING_PROFILES_ACTIVE=docker

  # problemservice:
  #   build: ./problemservice
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker

  codeexecutionservice:
    build: ./codeexecutionservice
    ports:
      - "8083:8083"
    depends_on:
      - mongo
      # - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  submissionservice:
    build: ./submissionservice
    ports:
      - "8084:8084"
    depends_on:
      - mongo
      # - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"  # RabbitMQ Management UI
