server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://root:password@mongo:27017/problemservice?authSource=admin
      username: root
      password: password
      database: admin

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/problemservice?authSource=admin
      username: root
      password: password
      database: admin
server:
  port: 8082

